export const metadata = {
    title: 'Register',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
  return (
    <html lang="en">
    <body style={{ "color": "red" }}>{children}</body>
    </html>
  )
  }
  